### ISSUE TITLE
download pdf button

### ISSUE THREAD

**Issue by manegame** [pwrstudio/readingresources#6]
In the original design, there is a **download pdf** button at the end of a text, after some white space. Visually appealing, but it risks being missed, since readers may stop scrolling after the text is done. 

![schermafbeelding 2016-08-24 om 16 07 39](https://cloud.githubusercontent.com/assets/17074938/17934121/072f3fd0-6a17-11e6-8b9b-0fe3c5e28fe0.png)
Proposed fixes

**in list**

![schermafbeelding 2016-08-24 om 16 17 49](https://cloud.githubusercontent.com/assets/17074938/17934120/0729fc32-6a17-11e6-99f8-8921aaf70ed6.png)

**top right**

![schermafbeelding 2016-08-24 om 16 21 38](https://cloud.githubusercontent.com/assets/17074938/17934119/07266626-6a17-11e6-9ffe-2861629714b7.png)

**Comment by pwrstudio** [comment]
Agree. but lets leave it where it is in the sketch for now. As it is not our design and I am not completely sure what the intentions of the download link is.

**Comment by manegame** [comment]
Ok!
