### ISSUE TITLE
Tether doing nothing after jQuery load

### ISSUE THREAD

**Issue by manegame** [pwrstudio/readingresources#7]
Images are not aligned to the spots they should be.  For instance when clicking on _understandings_. The image is just on the bottom. Not sure what the problem is. Something with the scope of JS?

**Comment by manegame** [comment]
Also, the image seems not to be centered in the right way anymore.

**Comment by pwrstudio** [comment]
Regarding first note: true. tether needs to be reloaded after the ajax-load. Will look at this tomorrow. 

Note two: Yes I noticed this. It seems to align correctly most of this time, but not always 
hmmm will check.
